on:
  push:
     branches:
       - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 8 * * *'

name: CHECK

jobs:
  bookdown:
    runs-on: windows-latest

    name: CHECK

    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e "install.packages(c('rmarkdown','bookdown'))"
      
      # Run example apsimx files
      - name: Checkout apsimx
        uses: actions/checkout@v2
        with:
            repository: APSIMInitiative/ApsimX
            path: ApsimX
            fetch-depth: 1
      - name: Checkout ApsimShared
        uses: actions/checkout@v2
        with:
            repository: APSIMInitiative/APSIM.Shared
            path: APSIM.Shared
            fetch-depth: 1
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Setup nuget
        uses: nuget/setup-nuget@v1
        with:
            nuget-version: '5.x'
      
      - name: Restore nuget
        run: nuget restore ApsimX.sln
        working-directory: ApsimX
        
      - name: Build ApsimX
        run: msbuild ApsimX.sln
        working-directory: ApsimX
        
      - name: Build ApsimX
        run: ls
        working-directory: ApsimX/bin
      
      - name: Run example apsimx files
        run: ../ApsimX/Bin/Models.exe *.apsimx
        working-directory: examples
      
      # Render book  
      - name: Render Book
        run: Rscript -e "bookdown::render_book('index.Rmd')"
